DROP DATABASE IF EXISTS `inalink`;

CREATE DATABASE IF NOT EXISTS `inalink`

CREATE TABLE IF NOT EXISTS `user`{
    `id` INT NOT NULL AUTO_INCREMENT,
    `firstname` VARCHAR(255) NOT NULL,
    `lastname` VARCHAR(255) NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `avatar` VARCHAR(255) NOT NULL
}

